SECRET_KEY = 'THIS IS AN INSECURE SECRET' 
SQLALCHEMY_DATABASE_URI = 'sqlite:///locusts.sqlite' 
CSRF_ENABLED = True
USER_ENABLE_EMAIL = True
USER_ENABLE_CHANGE_USERNAME = False
USER_ENABLE_USERNAME = False
